### ISSUE TITLE
Gene Order

### ISSUE THREAD

**Issue by bgsimon11** [Cosmic1Neko/Generative-models-for-bulk-RNA-Seq-data#1]
Hello, thanks for the excellent work here. I am interested in fine tuning your model on a different bulk RNAseq dataset, and in order to do so I need to know the order of genes in your input data so that I can process my dataset in the same way. Where can I find the data.Rdata object you used, or can you let me know the order of the genes in the object? Thanks!

**Comment by Cosmic1Neko** [comment]
Thank you for your recognition of this work! In `Generative-models-for-bulk-RNA-Seq-data/Inference/other.Rdata` [https://github.com/Cosmic1Neko/Generative-models-for-bulk-RNA-Seq-data/blob/master/Inference/other.Rdata](url)
, there is a variable `Ensembl_ID`, which is the “gene order” used by the model.
